### ISSUE TITLE
error for connceting Mist with Ethereum Wallet

### ISSUE THREAD

**Issue by hanyelsaid** [ethereum/grid#547]
I got this error when connecting mist with Ethereum Wallet

C:\Users\hp\AppData\Roaming>[2020-10-17T20:01:26.265] [INFO] Settings - Running in production mode: true
[2020-10-17T20:01:26.500] [INFO] EthereumNode - undefined 'fast' 'light'
[2020-10-17T20:01:26.507] [INFO] EthereumNode - Defaults loaded: geth ropsten fast
[2020-10-17T20:01:26.957] [INFO] main - Starting in Mist mode
[2020-10-17T20:01:27.100] [INFO] Db - Loading db: C:\Users\hp\AppData\Roaming\Mist\mist.lokidb
[2020-10-17T20:01:27.137] [INFO] Windows - Creating commonly-used windows
[2020-10-17T20:01:27.141] [INFO] Windows - Create secondary window: loading, owner: notset
[2020-10-17T20:01:27.568] [INFO] updateChecker - Check for update...
[2020-10-17T20:01:39.468] [INFO] Sockets/node-ipc - Connect to {"path":"ipc:\\\\.\\pipe\\geth.ipc"}
[2020-10-17T20:01:40.880] [INFO] Windows - Create primary window: main, owner: notset
[2020-10-17T20:01:41.039] [INFO] ClientBinaryManager - Initializing...
[2020-10-17T20:01:41.072] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2020-10-17T20:01:41.132] [INFO] main - Loading Interface at file://C:\Program Files\Mist\resources\app.asar/interface/index.html
[2020-10-17T20:01:41.443] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2020-10-17T20:01:42.249] [INFO] updateChecker - App is up-to-date.
[2020-10-17T20:01:42.262] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2020-10-17T20:01:42.269] [INFO] ClientBinaryManager - Initializing...
[2020-10-17T20:01:42.271] [INFO] ClientBinaryManager - Resolving platform...
[2020-10-17T20:01:42.277] [INFO] ClientBinaryManager - Calculating possible clients...
[2020-10-17T20:01:42.282] [INFO] ClientBinaryManager - 1 possible clients.
[2020-10-17T20:01:42.284] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2020-10-17T20:01:42.287] [INFO] ClientBinaryManager - Verify Geth status ...
[2020-10-17T20:01:42.321] [WARN] EthereumNodeRemote - Error from ws:  Error: Unexpected server response: 403
    at ClientRequest.req.on (C:\Program Files\Mist\resources\app.asar\node_modules\ws\lib\websocket.js:542:5)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)
[2020-10-17T20:01:42.349] [WARN] EthereumNodeRemote - Remote WebSocket connection closed (code: 1006). Reopening connection...
[2020-10-17T20:01:42.476] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2020-10-17T20:01:42.816] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2020-10-17T20:01:42.819] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2020-10-17T20:01:43.225] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.8.23" in Geth output
    at Promise.resolve.then.then.then (C:\Program Files\Mist\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:632:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2020-10-17T20:01:43.237] [INFO] ClientBinaryManager - Download binary for Geth ...
[2020-10-17T20:01:43.244] [INFO] ClientBinaryManager - Downloading package from https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.8.23-c9427004.zip to C:\Users\hp\AppData\Roaming\Mist\binaries\Geth\archive.zip ...
[2020-10-17T20:01:43.496] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2020-10-17T20:01:44.431] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2020-10-17T20:01:44.442] [WARN] EthereumNode - Failed to connect to an existing local node. Starting our own...
[2020-10-17T20:01:44.445] [INFO] EthereumNode - Node type: geth
[2020-10-17T20:01:44.452] [INFO] EthereumNode - Network: ropsten
[2020-10-17T20:01:44.456] [INFO] EthereumNode - SyncMode: fast
[2020-10-17T20:01:44.461] [INFO] EthereumNode - Start node: geth ropsten fast
[2020-10-17T20:01:44.473] [ERROR] EthereumNode - Failed to start node Error: Node "geth" binPath is not available.
    at EthereumNode.__startNode (C:\Program Files\Mist\resources\app.asar\modules\ethereumNode.js:374:13)
    at stop.then (C:\Program Files\Mist\resources\app.asar\modules\ethereumNode.js:300:19)
    at tryCatcher (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Unhandled rejection Error: Node "geth" binPath is not available.
    at EthereumNode.__startNode (C:\Program Files\Mist\resources\app.asar\modules\ethereumNode.js:374:13)
    at stop.then (C:\Program Files\Mist\resources\app.asar\modules\ethereumNode.js:300:19)
    at tryCatcher (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[2020-10-17T20:02:00.863] [INFO] (ui: popupWindow) - Meteor starting up...
[2020-10-17T20:02:13.530] [INFO] (ui: popupWindow) - Meteor starting up...
[2020-10-17T20:02:15.220] [INFO] (ui: mist) - Meteor starting up...
[2020-10-17T20:02:15.277] [INFO] (ui: mist) - Initialize Mist Interface
[2020-10-17T20:03:22.331] [ERROR] ClientBinaryManager - Error: Hash mismatch (using md5): expected e05524cc4f6e8711645f40ef5921918a; got ec8fbd9ec338aa78fbf0eba51edbff17
    at checksum.then (C:\Program Files\Mist\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:291:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2084) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Hash mismatch (using md5): expected e05524cc4f6e8711645f40ef5921918a; got ec8fbd9ec338aa78fbf0eba51edbff17
(node:2084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-10-17T20:03:28.978] [INFO] main - Defer quitting until sockets and node are shut down
[2020-10-17T20:03:28.983] [INFO] Sockets - Destroy all sockets
[2020-10-17T20:03:28.986] [INFO] Sockets/2 - Disconnecting...
[2020-10-17T20:03:28.990] [INFO] Sockets/3 - Disconnecting...
[2020-10-17T20:03:28.992] [INFO] Sockets/node-ipc - Disconnecting...
[2020-10-17T20:03:29.075] [ERROR] main - Error shutting down sockets
[2020-10-17T20:03:29.601] [INFO] main - About to quit...
[2020-10-17T20:03:29.841] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2020-10-17T20:03:29.843] [INFO] main - About to quit...
[2020-10-17T20:03:30.172] [INFO] Windows - All primary windows closed/invisible, so quitting app...

C:\Users\hp\AppData\Roaming>cls

**Comment by hanyelsaid** [comment]
Appreciate your feedback
